name: CI

on:
  push:
    branches:
      - introduce-tests
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-dist
        with:
          path: .
          key: ${{ github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'

      - name: Install, build and start
        run: |
          npm ci
          npm run build
          npm run env start

  test:
    runs-on: ubuntu-latest
    needs: [build]
   
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-dist
        with:
          path: .
          key: ${{ github.sha }}

      - name: install playwright
        run: |
          npm install -D @playwright/test
          npx playwright install chromium

      - name: run test for develop
        run: |
          npx playwright test tests/addSource.test.js
