name: CI

on:
  push:
    branches:
      - introduce-tests
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-dist
        with:
          path: .
          key: ${{ github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'

      - name: Install dependecies
        run: |
          npm ci

      - name: Build js
        run: |
          npm run build

  test:
    runs-on: ubuntu-latest
    needs: [build]
   
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-dist
        with:
          path: .
          key: ${{ github.sha }}

      - name: install playwright
        run: |
          npm install -D @playwright/test
          npx playwright install

      - name: run test for develop
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        if: github.ref == 'refs/heads/develop'
        run: |
          URL=https://develop.sharepicgenerator.de/ PASS=$PASSWORD npx playwright test tests/create-sharepic.spec.js
