name: CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wpVersion: ['6.2', '6.3', '6.4', '6.5']
        phpVersion: ['8.0', '8.1', '8.2']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache-dist
        with:
          path: .
          key: ${{ github.sha }}
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.phpVersion }}
          dev: no
      - uses: actions/setup-node@v4
        with:
          node-version: '19.x'

      # PHP Dependencies
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup WordPress and our plugin
        run: |
          npm ci
          npm run build
          WP_ENV_CORE=wordpress/wordpress#${{ matrix.wpVersion }} WP_ENV_PHP_VERSION=${{ matrix.phpVersion }} npm run env start

      - name: Install playwright
        run: |

          npm install -D @playwright/test
          npx playwright install chromium

      - name: Run test
        run: |
          npx playwright test

      - name: Archive test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report
