name: CI

on:
  push:
    branches:
      - improve-tests

jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-dist
        with:
          path: .
          key: ${{ github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'

      - name: Setup WordPress and our plugin
        run: | 
          npm ci
          npm run build 
          npm run env start

      - name: Install playwright
        run: |
          npm install -D @playwright/test
          npx playwright install chromium
            
      - name: Run test
        run: |
          npx playwright test tests/addSource.test.js

      - name: Archive test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: |
            playwright-report
